syntax = "proto3";
package zzz.messages;

import "task.proto";
import "vfs.proto";

message GetAgentServerCommand {
  uint64 project_id = 1;
  string name = 2;
  reserved 3;
  reserved "root_dir";
}

message GetContextServerCommand {
  uint64 project_id = 1;
  string server_id = 2;
  reserved 3;
  reserved "root_dir";
}

message ContextServerCommand {
  reserved 1;
  reserved "path";
  repeated string args = 2;
  map<string, string> env = 3;
  NativePathV2 path_v2 = 4;
}

message AgentServerCommand {
  reserved 1;
  reserved "path";
  repeated string args = 2;
  map<string, string> env = 3;
  reserved 4;
  reserved "root_dir";

  optional SpawnInTerminal login = 5;
  NativePathV2 path_v2 = 6;
}

message ExternalAgentsUpdated {
  uint64 project_id = 1;
  repeated string names = 2;
}

message ExternalAgentLoadingStatusUpdated {
  uint64 project_id = 1;
  string name = 2;
  reserved 3;
}

message NewExternalAgentVersionAvailable {
  uint64 project_id = 1;
  string name = 2;
  string version = 3;
}
