syntax = "proto3";
package zzz.messages;

import "vfs.proto";

message ListToolchains {
  uint64 project_id = 1;
  uint64 worktree_id = 2;
  string language_name = 3;
  reserved 4;
  reserved "path";
  VfsPathV2 path_v2 = 5;
}

message Toolchain {
  string name = 1;
  reserved 2;
  reserved "path";
  string raw_json = 3;
  NativePathV2 path_v2 = 4;
}

message ToolchainGroup {
  uint64 start_index = 1;
  string name = 2;
}

message ListToolchainsResponse {
  repeated Toolchain toolchains = 1;
  bool has_values = 2;
  repeated ToolchainGroup groups = 3;
  reserved 4;
  reserved "relative_worktree_path";
  VfsPathV2 relative_worktree_path_v2 = 5;
}

message ActivateToolchain {
  uint64 project_id = 1;
  uint64 worktree_id = 2;
  Toolchain toolchain = 3;
  string language_name = 4;
  reserved 5;
  reserved "path";
  VfsPathV2 path_v2 = 6;
}

message ActiveToolchain {
  uint64 project_id = 1;
  uint64 worktree_id = 2;
  string language_name = 3;
  reserved 4;
  reserved "path";
  VfsPathV2 path_v2 = 5;
}

message ActiveToolchainResponse {
  optional Toolchain toolchain = 1;
}

message ResolveToolchain {
  uint64 project_id = 1;
  reserved 2;
  reserved "abs_path";
  string language_name = 3;
  NativePathV2 abs_path_v2 = 4;
}

message ResolveToolchainResponse {
  oneof response {
    Toolchain toolchain = 1;
    string error = 2;
  }
}
