[package]
name = "perf"
version = "0.1.0"
publish = false
edition.workspace = true
license = "AGPL-3.0-or-later"
description = "A tool for measuring ZZZ test performance, with too many Clippy lints"

[lib]

[lints]
workspace = true

[dependencies]
collections.workspace = true
serde.workspace = true
serde_json.workspace = true
