[package]
name = "perf"
version = "0.1.0"
publish = false
edition.workspace = true
license = "Apache-2.0"
description = "A tool for measuring Zed test performance, with too many Clippy lints"

[lib]

[lints]
workspace = true

[dependencies]
collections.workspace = true
serde.workspace = true
serde_json.workspace = true
