#!/usr/bin/env bash

set -euo pipefail

if [[ ! " $* " == *" -p "* && ! " $* " == *" --package "* ]]; then
    set -- "$@" --workspace
fi

if command -v ccache >/dev/null 2>&1 && [[ -z "${CCACHE_DIR:-}" ]]; then
    ccache_dir="$(ccache --get-config cache_dir)"
    ccache_parent_dir="$(dirname "$ccache_dir")"

    if [[ ! -d "$ccache_dir" && ! -w "$ccache_parent_dir" ]] || [[ -d "$ccache_dir" && ! -w "$ccache_dir" ]]; then
        export CCACHE_DIR="$(pwd)/target/ccache"
        mkdir -p "$CCACHE_DIR"
    fi
fi

set -x
"${CARGO:-cargo}" clippy "$@" --release --all-targets --all-features -- --deny warnings

# If local, run other checks if we have the tools installed.
if [[ -z "${GITHUB_ACTIONS+x}" ]]; then
    which cargo-machete >/dev/null 2>&1 || exit 0
    cargo machete

    which typos >/dev/null 2>&1 || exit 0
    typos --config typos.toml

    which buf >/dev/null 2>&1 || exit 0
    buf lint crates/proto/proto
    buf format --diff --exit-code crates/proto/proto
fi
