name = "XSD"
grammar = "xml"
query_layers = ["shared/xml_dtd", "xml"]
path_suffixes = ["xsd"]
first_line_pattern = '^\s*<\?xml\b'
block_comment = ["<!-- ", " -->"]
brackets = [{ start = "<", end = ">", close = true, newline = true }]
prettier_parser_name = "xml"
prettier_plugins = ["@prettier/plugin-xml"]
