[package]
name = "edit_prediction_metrics"
version = "0.1.0"
publish.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/edit_prediction_metrics.rs"

[dependencies]
serde.workspace = true
tree-sitter.workspace = true

[dev-dependencies]
indoc.workspace = true
