[package]
name = "zzz_test_extension"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "AGPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/test_extension.rs"
crate-type = ["cdylib"]

[dependencies]
zzz_extension_api = { path = "../../crates/extension_api" }
